/**
 * contracts-seed.ts — Cartera contractual auditada (45 relaciones).
 *
 * FUENTE DE VERDAD: «Auditoría Contractual Integral — Verotin S.A. / Logística TOPS»
 * (PDF, fecha de corte 13/06/2026) + maqueta oficial «TOPS NEXUS · Módulo Contratos» (HTML).
 *
 * Estos 45 registros son la CARGA INICIAL del módulo (Roadmap Fase 2 — MVP). El módulo
 * los usa como fallback de solo-lectura mientras la tabla `public.contracts` (migración
 * 0076) no esté poblada en la base conectada. No editar a mano: regenerado desde la
 * maqueta para evitar divergencias. Importes ARS/USD a valor documentado; «desact» marca
 * cánones a valor histórico de origen (el vigente por índice CEDOL/IPCBA es superior).
 */
import type { ContractRecord, ContractsAggregates } from "./contracts-types";

/** Fecha de corte de la auditoría (cálculo de semáforo, meses restantes y alertas). */
export const AUDIT_CORTE = "2026-06-13";

/** Cartera auditada — 45 relaciones (35 ANMAT + 10 Cargas Generales). */
export const CONTRACTS_SEED: ContractRecord[] = [
  {
    "n": "DEO Distribuidora de Equipos Odontológicos S.A.",
    "cuit": "30-71911511-6",
    "tipo": "ANMAT",
    "canon": 4000000,
    "mon": "ARS",
    "m2": 50,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2026-06-01",
    "venc": "2028-05-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Ajuste semestral (resto trimestral); acuse firmado 02-08-26 posterior al inicio; dualidad normativa contrato/condiciones",
    "dias_venc": 718,
    "meses_rest": 23.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "21/05/2026",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Unificar contrato y condiciones; pasar el ajuste a trimestral; regularizar la fecha del acuse.",
    "pen": "Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día."
  },
  {
    "n": "PEGHI Commerce S.A.S.",
    "cuit": "30-71925571-6",
    "tipo": "ANMAT",
    "canon": 1500000,
    "mon": "ARS",
    "m2": 17,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2026-02-01",
    "venc": "2027-01-31",
    "renov": true,
    "riesgo": "Bajo",
    "estado": "Vigente",
    "desact": false,
    "hall": "Firma digital certificada; omisión de 'm²' en cl.1.1",
    "dias_venc": 232,
    "meses_rest": 7.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "04/02/2026",
    "plazo": "12 m",
    "preaviso": "30 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Corregir la omisión de «m²» en cl. 1.1; iniciar la renovación anticipadamente.",
    "pen": "Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 1, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + cláusula penal 2 cánones + 10% + ocupación U$S200/día."
  },
  {
    "n": "RO Latin Medical Argentina S.R.L.",
    "cuit": "30-71899606-2",
    "tipo": "ANMAT",
    "canon": 1350000,
    "mon": "ARS",
    "m2": 38,
    "ubic": "Nave 5 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2026-01-01",
    "venc": "2027-12-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Contrato bajo razón social anterior (cambio de denominación); régimen de responsabilidad Art.1376 más gravoso; penalidades reducidas",
    "dias_venc": 566,
    "meses_rest": 18.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "08/01/2026",
    "plazo": "24 m",
    "preaviso": "60–90 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Adenda urgente por cambio de denominación social; alinear el régimen de responsabilidad y elevar el tope de penalidades.",
    "pen": "Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 2, máx. 3 cánones) + cláusula penal 2 cánones + 10% + ocupación U$S200/día. NO incluye la multa del 10% del Art. 1221 (penalidad reducida vs. el modelo estándar)."
  },
  {
    "n": "Vitalis Pharma S.A.",
    "cuit": "30-71916753-1",
    "tipo": "ANMAT",
    "canon": 1890000,
    "mon": "ARS",
    "m2": 65,
    "ubic": "Pedro de Luján 3151/3181",
    "ini": "2025-12-01",
    "venc": "2027-11-30",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Vigente",
    "desact": false,
    "hall": "ERROR tipográfico vencimiento '207'; doble firmante sin personería; propuesta posterior al contrato; domicilios contradictorios",
    "dias_venc": 535,
    "meses_rest": 17.8,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "10/12/2025",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "ADENDA URGENTE: corregir el año de vencimiento «207»→2027; acreditar personería del firmante; unificar domicilios.",
    "pen": "Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día."
  },
  {
    "n": "PADECO S.A.",
    "cuit": "30-70828842-6",
    "tipo": "ANMAT",
    "canon": 792000,
    "mon": "ARS",
    "m2": 17,
    "ubic": "Unidad 9 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2025-11-01",
    "venc": "2026-10-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Próximo a vencer; sin mínimo en indemnización sustitutiva",
    "dias_venc": 140,
    "meses_rest": 4.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "28/10/2025",
    "plazo": "12 m",
    "preaviso": "30 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Iniciar la renovación ya (vence 31/10/2026); fijar un mínimo de indemnización sustitutiva.",
    "pen": "Indemnización sustitutiva: 1 canon por cada 30 días omitidos (sin mínimo expreso, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + cláusula penal 2 cánones + 10% + ocupación U$S200/día. (Laguna: no fija piso de indemnización.)"
  },
  {
    "n": "LION BUSINES S.R.L.",
    "cuit": "30-71903156-7",
    "tipo": "ANMAT",
    "canon": 765000,
    "mon": "ARS",
    "m2": 56.97,
    "ubic": "Unidad 7 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2025-08-01",
    "venc": "2027-07-31",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Vigente",
    "desact": false,
    "hall": "Adenda amplió superficie +42% SIN modificar canon; dos versiones de adenda; razón social con posible error",
    "dias_venc": 413,
    "meses_rest": 13.8,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "05/08/2025",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "URGENTE: adenda que fije el canon de los 56,97 m²; unificar las dos versiones de la adenda.",
    "pen": "Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día."
  },
  {
    "n": "Business For Pharma S.R.L.",
    "cuit": "30-71871534-9",
    "tipo": "ANMAT",
    "canon": 1000000,
    "mon": "ARS",
    "m2": 38,
    "ubic": "Unidad 1 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2025-07-01",
    "venc": "2027-06-30",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Canon duplicado por adenda el mismo día; cl.2.1 renovación contradictoria",
    "dias_venc": 382,
    "meses_rest": 12.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "14/07/2025",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Corregir la contradicción de la cl. 2.1 (renovación); jerarquizar contrato vs. condiciones generales.",
    "pen": "Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día."
  },
  {
    "n": "Korean Skin S.R.L.",
    "cuit": "30-71860717-1",
    "tipo": "ANMAT",
    "canon": 400000,
    "mon": "ARS",
    "m2": 20,
    "ubic": "Unidad 6 - Magaldi 1765",
    "ini": "2025-02-01",
    "venc": "2027-01-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": true,
    "hall": "Canon feb-2025 sin actualización CEDOL documentada; renovación hasta 4 períodos (compromiso 10 años)",
    "dias_venc": 232,
    "meses_rest": 7.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "11/02/2025",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Documentar los ajustes CEDOL aplicados; cuantificar la indemnización por rescisión.",
    "pen": "El contrato remite a los arts. 1221/1199/2587-2593 CCyCN; las Condiciones Generales cuantifican: 1 mes de alquiler por cada 30 días omitidos (mín. 2 meses) + ocupación U$S200/día. (No cuantificada en el cuerpo del contrato.)"
  },
  {
    "n": "ROBI Insumos Médicos S.R.L.",
    "cuit": "30-71878091-4",
    "tipo": "ANMAT",
    "canon": 1300000,
    "mon": "ARS",
    "m2": 17,
    "ubic": "Unidad 7 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2026-01-01",
    "venc": "2027-12-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Firma electrónica certificada; condiciones generales con domicilio en blanco; firmadas antes que el contrato",
    "dias_venc": 566,
    "meses_rest": 18.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "06/01/2026",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Completar el domicilio en las condiciones generales; alinear fechas de firma.",
    "pen": "Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día."
  },
  {
    "n": "Silvia Noemí Willging",
    "cuit": "27-13782891-5",
    "tipo": "ANMAT",
    "canon": 1600000,
    "mon": "ARS",
    "m2": 70,
    "ubic": "Nave 3 Unidad 5 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2025-11-01",
    "venc": "2027-10-31",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Vigente",
    "desact": false,
    "hall": "Persona física sin garantías; domicilio en La Pampa; hash de certificación inválido (string vacío)",
    "dias_venc": 505,
    "meses_rest": 16.8,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "30/10/2025",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Exigir garantía/fianza (persona física, domicilio en el interior); reemitir condiciones con hash de firma válido.",
    "pen": "Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día."
  },
  {
    "n": "Medical Inputs S.R.L.",
    "cuit": "30-71860398-2",
    "tipo": "ANMAT",
    "canon": 500000,
    "mon": "ARS",
    "m2": 30,
    "ubic": "Unidad 2 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2024-09-01",
    "venc": "2026-08-31",
    "renov": true,
    "riesgo": "Crítico",
    "estado": "Vigente",
    "desact": true,
    "hall": "URGENTE: preaviso de no renovación vence 02/07/2026; canon base sep-2024 sin actualizar (6 ajustes pendientes)",
    "dias_venc": 79,
    "meses_rest": 2.6,
    "semaforo": "Amarillo",
    "semaforo_label": "60-90 días",
    "firma": "28/08/2024",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "ACCIÓN ANTES DEL 02/07/2026 (preaviso de no renovación); actualizar el canon (6 ajustes pendientes).",
    "pen": "El contrato remite a los arts. 1221/1199/2587-2593 CCyCN; Condiciones Generales: 1 mes de alquiler por cada 30 días omitidos (mín. 2 meses) + ocupación U$S200/día."
  },
  {
    "n": "Migliore S.R.L.",
    "cuit": "30-71475048-4",
    "tipo": "ANMAT",
    "canon": 900000,
    "mon": "ARS",
    "m2": 25,
    "ubic": "Unidad 6 PB - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2025-09-01",
    "venc": "2027-08-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Condiciones firmadas 23 días antes del contrato; posible superposición de Unidad 6 con Korean Skin",
    "dias_venc": 444,
    "meses_rest": 14.8,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "19/09/2025",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Verificar superposición de la Unidad 6 con Korean Skin; reconocer la retroactividad por adenda.",
    "pen": "Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día."
  },
  {
    "n": "Bio Analítica Argentina S.A.",
    "cuit": "30-70753876-3",
    "tipo": "ANMAT",
    "canon": 2525696,
    "mon": "ARS",
    "m2": 50,
    "ubic": "Nave 3 Unidad 4 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2025-08-01",
    "venc": "2026-10-31",
    "renov": true,
    "riesgo": "Crítico",
    "estado": "En-Conflicto",
    "desact": false,
    "hall": "Contrato RESCINDIDO por mora (CD abr-2026, deuda ~$11M); acuerdo informal de regularización pago adelantado may-oct 2026 SIN nuevo instrumento firmado",
    "dias_venc": 140,
    "meses_rest": 4.7,
    "semaforo": "Naranja",
    "semaforo_label": "En conflicto / acuerdo transitorio",
    "firma": "06/08/2025",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "URGENTE: formalizar el acuerdo de mayo 2026 como nuevo instrumento; acreditar el cobro de los cheques.",
    "pen": "Omisión de preaviso = indemnización sustitutiva de 2 cánones; cláusula penal por incumplimiento 2 cánones + 10%; ocupación U$S200/día; mora en pago: interés punitorio 3× tasa activa BNA + derecho de retención de mercadería."
  },
  {
    "n": "MEDIMPO S.R.L.",
    "cuit": "30-71849548-9",
    "tipo": "ANMAT",
    "canon": 1000000,
    "mon": "ARS",
    "m2": 50,
    "ubic": "Magaldi 1765 (UF 3.1/3.2)",
    "ini": "2024-03-02",
    "venc": "2028-03-01",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Renovación automática operada (01/03/2026) no documentada; canon base mar-2024 sin actualizar; hasta 4 períodos",
    "dias_venc": 627,
    "meses_rest": 20.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "03/05/2024",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Documentar la renovación de 03/2026; actualizar el canon; verificar habilitaciones por unidad funcional.",
    "pen": "Omisión de preaviso = mín. 2 meses de alquiler (1 mes por cada 30 días); ocupación U$S200/día; mora: 3× tasa activa BNA + retención; incumplimiento: cánones pendientes hasta fin de plazo + U$S200/día."
  },
  {
    "n": "INGEMED S.A.",
    "cuit": "30-71245879-4",
    "tipo": "ANMAT",
    "canon": 162000,
    "mon": "ARS",
    "m2": 10,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2024-01-02",
    "venc": "2028-01-01",
    "renov": true,
    "riesgo": "Bajo",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Contrato legalizado ante escribana (el más robusto); CUIT VEROTIN mal tipeado en cl.4.3; canon base ene-2024 sin actualizar",
    "dias_venc": 567,
    "meses_rest": 18.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "26/12/2023",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Corregir el CUIT de VEROTIN en cl. 4.3; documentar la renovación; incorporar el cargo de desconsolidado.",
    "pen": "Omisión de preaviso = mín. 2 meses de alquiler; ocupación U$S200/día; mora: 3× tasa activa BNA + retención de mercadería."
  },
  {
    "n": "Medicina del Plata S.R.L.",
    "cuit": "30-71822590-2",
    "tipo": "ANMAT",
    "canon": 616200,
    "mon": "ARS",
    "m2": 70,
    "ubic": "Depósito 5 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2023-11-13",
    "venc": "2027-11-12",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Adenda abr-2025 solo en Google Doc sin firma; canon base nov-2023 sin actualizar",
    "dias_venc": 517,
    "meses_rest": 17.2,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "01/11/2023",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Obtener la adenda firmada (hoy solo Google Doc); anexar tarifas de servicios; documentar la renovación.",
    "pen": "Omisión de preaviso = mín. 2 meses de alquiler; ocupación U$S200/día; mora: 3× tasa activa BNA + retención de mercadería."
  },
  {
    "n": "WINTRADE S.A.",
    "cuit": "30-71466762-5",
    "tipo": "ANMAT",
    "canon": 349440,
    "mon": "ARS",
    "m2": 60,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2023-08-15",
    "venc": "2027-08-14",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Descuento 30% condicionado a pago semestral sin verificación; ajuste semestral; canon base ago-2023",
    "dias_venc": 427,
    "meses_rest": 14.2,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "17/08/2023",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Cláusula de reversión de precio si no se paga el semestre adelantado; migrar a ajuste trimestral.",
    "pen": "Omisión de preaviso = mín. 2 meses de alquiler; ocupación U$S200/día; mora: 3× tasa activa BNA + retención de mercadería."
  },
  {
    "n": "Q-ADVICE S.A.S.",
    "cuit": "30-71710748-5",
    "tipo": "ANMAT",
    "canon": 200000,
    "mon": "ARS",
    "m2": 30,
    "ubic": "Pedro de Luján 3151/3181",
    "ini": "2023-08-01",
    "venc": "2027-07-31",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "CUIT al pie ≠ encabezado; doble cláusula 4.3; contradicción provisión de pallets; canon base ago-2023",
    "dias_venc": 413,
    "meses_rest": 13.8,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "01/08/2023",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Corregir el CUIT del cliente; verificar la habilitación ANMAT del depósito de Luján; aclarar provisión de pallets.",
    "pen": "Omisión de preaviso = mín. 2 meses de alquiler; ocupación U$S200/día; mora: 3× tasa activa BNA + retención de mercadería."
  },
  {
    "n": "Panalab Argentina S.A.",
    "cuit": "30-65812709-4",
    "tipo": "ANMAT",
    "canon": 161100,
    "mon": "ARS",
    "m2": 12,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765 (depósito + oficina)",
    "ini": "2023-01-18",
    "venc": "2026-12-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Instrumento 'Carta Oferta' atípico; ajuste IPCBA (no CEDOL); oficina sin contrato autónomo; superficie depósito no consignada",
    "dias_venc": 201,
    "meses_rest": 6.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "18/01/2023",
    "plazo": "≈24 m",
    "preaviso": "60 días",
    "ajuste": "IPCBA semestral",
    "reco": "Regularizar la oficina con contrato propio; unificar el índice de ajuste; consignar la superficie del depósito.",
    "pen": "Carta Oferta (locación): al cursar el preaviso, el cliente abona 2 cánones mensuales; mora en devolución del depósito U$S100/día. (Cl. 1.4 excluye indemnizaciones adicionales — interpretar armónicamente con 1.3.)"
  },
  {
    "n": "KODENT S.A.",
    "cuit": "30-71005846-2",
    "tipo": "ANMAT",
    "canon": 2603442,
    "mon": "ARS",
    "m2": 37,
    "ubic": "Depósitos 5 y 8 - Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2022-11-15",
    "venc": "2026-11-14",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": false,
    "hall": "Único con planilla de ajustes (mejor gestionado); frecuencia cambiada de facto semestral→trimestral sin adenda; error en 1er ajuste",
    "dias_venc": 154,
    "meses_rest": 5.1,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "14/11/2022",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL (de facto trimestral)",
    "reco": "Adenda que formalice la frecuencia trimestral y el canon vigente; subsanar el error del 1er ajuste.",
    "pen": "Falta de preaviso (60 días) = equivalente a los días de preaviso omitidos; incumplimiento de uso (cl. 3.3): alquileres pendientes hasta fin de plazo + U$S50/día; mora en devolución al vencimiento U$S100/día."
  },
  {
    "n": "ELINTEC S.A.",
    "cuit": "30-71422762-5",
    "tipo": "ANMAT",
    "canon": 60000,
    "mon": "ARS",
    "m2": 16,
    "ubic": "Pedro de Luján 3151/3181",
    "ini": "2022-08-15",
    "venc": "2026-08-14",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "4 años sin actualización ni adenda; INCONSISTENCIA de dirección cl.1ª (Luján) vs cl.9ª (Magaldi) con riesgo ANMAT; canon base ago-2022",
    "dias_venc": 62,
    "meses_rest": 2.1,
    "semaforo": "Amarillo",
    "semaforo_label": "60-90 días",
    "firma": "25/08/2022",
    "plazo": "12 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "URGENTE: corregir la inconsistencia de dirección (Luján vs. Magaldi) por su impacto ANMAT; adenda con canon actualizado.",
    "pen": "Falta de preaviso = equivalente a los días omitidos; incumplimiento de uso: alquileres pendientes + U$S100/día; mora en devolución al vencimiento U$S200/día."
  },
  {
    "n": "AMAOTO S.R.L.",
    "cuit": "30-71682677-1",
    "tipo": "ANMAT",
    "canon": 65000,
    "mon": "ARS",
    "m2": 17,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2022-04-01",
    "venc": "2028-03-31",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Venció 31/03/2026; renovación automática presunta no instrumentada; canon base $65.000 irreal; anexo de cubículos ene-2026 sin firmar",
    "dias_venc": 657,
    "meses_rest": 21.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "29/03/2022",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Firmar nuevo contrato/adenda con el canon real; instrumentar la eventual migración a cubículos.",
    "pen": "Falta de preaviso = equivalente a los días omitidos; incumplimiento de uso: alquileres pendientes + U$S100/día; mora en devolución al vencimiento U$S200/día."
  },
  {
    "n": "Forever Living Products Argentina S.R.L.",
    "cuit": "33-66345385-4",
    "tipo": "ANMAT",
    "canon": 303914,
    "mon": "ARS",
    "m2": 65,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765 (2 depósitos)",
    "ini": "2022-11-01",
    "venc": "2026-10-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Discordancia de CUIT entre documentos (33- vs 30-); deslinde 2021 sin firmante identificado; canon base nov-2022",
    "dias_venc": 140,
    "meses_rest": 4.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "21/12/2022",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Verificar y unificar el CUIT; completar el deslinde; documentar los ajustes.",
    "pen": "Falta de preaviso = equivalente a los días omitidos; incumplimiento de uso: alquileres pendientes + U$S100/día; mora en devolución al vencimiento U$S200/día."
  },
  {
    "n": "Dana Yasmín Atena",
    "cuit": "29-39428293-1",
    "tipo": "ANMAT",
    "canon": 127710,
    "mon": "ARS",
    "m2": 17,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2023-02-01",
    "venc": "2027-01-31",
    "renov": true,
    "riesgo": "Crítico",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "ERROR tipográfico año de firma '2323'; persona física por apoderada sin verificar poder; venció 31/01/2026 sin instrumento nuevo; canon base feb-2023",
    "dias_venc": 232,
    "meses_rest": 7.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "15/02/2023",
    "plazo": "12 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "URGENTE: nuevo contrato que subsane el año «2323» y fije el canon; verificar el poder de la apoderada.",
    "pen": "Falta de preaviso = equivalente a los días omitidos; incumplimiento de uso: alquileres pendientes + U$S100/día; mora en devolución al vencimiento U$S200/día."
  },
  {
    "n": "Royal Packs S.A.",
    "cuit": "30-71690136-6",
    "tipo": "ANMAT",
    "canon": 3231200,
    "mon": "ARS",
    "m2": 400,
    "ubic": "Nave II - Magaldi 1765",
    "ini": "2024-03-13",
    "venc": "2028-03-12",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": false,
    "hall": "Penalidad U$S200/día sin tope; propuesta decía ajuste semestral vs contrato trimestral; renovó automáticamente 03/2026",
    "dias_venc": 638,
    "meses_rest": 21.3,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "25/03/2024",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Tope de días para ocupación extemporánea (U$S200/día sin tope); unificar contrato + condiciones.",
    "pen": "Indemnización por preaviso omitido = mín. 2 meses de alquiler (calculado sobre el mes de mayor valor del año anterior) + ocupación extemporánea U$S200/día; aplican arts. 1221/1199/2587-2593 CCyCN."
  },
  {
    "n": "TINU S.R.L.",
    "cuit": "30-71547481-2",
    "tipo": "ANMAT",
    "canon": 39000,
    "mon": "ARS",
    "m2": 17,
    "ubic": "Osvaldo Cruz 3201 / Magaldi 1765",
    "ini": "2020-10-01",
    "venc": "2026-09-30",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Sin tope de renovaciones; doble dirección; canon base 2020 ($39.000) sin historial de ajustes",
    "dias_venc": 109,
    "meses_rest": 3.6,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "01/10/2020",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Adenda con canon actualizado, dirección única y tope de renovaciones automáticas.",
    "pen": "Preaviso de 60 días o pago sustitutivo; ocupación extemporánea U$S200/día; por incumplimiento de uso: cánones pendientes hasta fin de plazo + U$S100/día."
  },
  {
    "n": "Técnicas Mínimo Invasivas S.A.",
    "cuit": "30-71138635-8",
    "tipo": "ANMAT",
    "canon": 143879,
    "mon": "ARS",
    "m2": 50,
    "ubic": "Magaldi 1765",
    "ini": "2022-01-01",
    "venc": "2027-12-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Renovación 36m no formalizada (Google Doc sin firma); penalidad U$S100/día (más baja); canon base ene-2022",
    "dias_venc": 566,
    "meses_rest": 18.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "03/01/2022",
    "plazo": "36 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Formalizar la renovación con firma; documentar ajustes; elevar la penalidad a U$S200/día.",
    "pen": "Preaviso de 60 días o pago sustitutivo (mín. 2 meses según Condiciones Generales); ocupación extemporánea U$S200/día; incumplimiento de uso: cánones pendientes + U$S100/día."
  },
  {
    "n": "Compañía de Higiene S.R.L.",
    "cuit": "33-71228608-9",
    "tipo": "ANMAT",
    "canon": 72500,
    "mon": "ARS",
    "m2": 50,
    "ubic": "Magaldi 1765",
    "ini": "2020-05-01",
    "venc": "2029-04-30",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Relación más antigua (2020); cl.2.1 sin plazo de preaviso legible; sin tope de renovaciones; canon base 2020 más desactualizado",
    "dias_venc": 1052,
    "meses_rest": 35.1,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "04/05/2020",
    "plazo": "36 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Adenda: actualizar canon, fijar preaviso claro y tope de renovaciones; verificar el preaviso ya operado.",
    "pen": "Preaviso de 60 días o equivalente dinerario; ocupación extemporánea U$S200/día; incumplimiento de uso: cánones pendientes hasta fin de plazo + U$S100/día."
  },
  {
    "n": "ULTRALINE S.A.",
    "cuit": "30-68076098-1",
    "tipo": "ANMAT",
    "canon": 3970429,
    "mon": "ARS",
    "m2": 530,
    "ubic": "Pedro de Luján 3159",
    "ini": "2023-10-01",
    "venc": "2026-09-30",
    "renov": true,
    "riesgo": "Crítico",
    "estado": "En-Litigio",
    "desact": false,
    "hall": "Cliente bajo INTERVENCIÓN JUDICIAL; deuda impaga ~$30M (nov-dic 2024); derecho de retención ejercido; resolución judicial jul-2025",
    "dias_venc": 109,
    "meses_rest": 3.6,
    "semaforo": "Negro",
    "semaforo_label": "En litigio",
    "firma": "29/09/2023",
    "plazo": "36 m",
    "preaviso": "180 días",
    "ajuste": "CEDOL trimestral",
    "reco": "URGENTE (legal): ejecutar retención y cobro (~$30M); verificar la resolución judicial de jul-2025; tasar el stock.",
    "pen": "Rescisión anticipada por el cliente: preaviso de 180 días corridos o pago sustitutivo; ocupación extemporánea U$S100/día; incumplimiento de uso: cánones pendientes + U$S100/día. (VEROTIN puede rescindir sin causa con 180 días.)"
  },
  {
    "n": "NARENA S.R.L.",
    "cuit": "30-71441661-4",
    "tipo": "ANMAT",
    "canon": 1700000,
    "mon": "ARS",
    "m2": 18,
    "ubic": "1° Piso Unidad 1 - Pedro de Luján 3151/3181",
    "ini": "2026-03-01",
    "venc": "2028-02-29",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Contrato firmado + adenda; bonif. extensible por demoras sin tope; firmante apoderada sin certificación notarial",
    "dias_venc": 626,
    "meses_rest": 20.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "27/02/2026",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Aclarar la modalidad de renovación; topear la bonificación por demoras de obra; archivar seguros.",
    "pen": "Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + ocupación U$S200/día."
  },
  {
    "n": "TEX ARGENTA S.R.L.",
    "cuit": "30-68030867-1",
    "tipo": "ANMAT",
    "canon": 1700000,
    "mon": "ARS",
    "m2": 18,
    "ubic": "1° Piso Unidad 2 - Pedro de Luján 3151/3181",
    "ini": "2026-03-01",
    "venc": "2028-02-29",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Vigente",
    "desact": false,
    "hall": "Inicio retroactivo 20 días sin contrato; discrepancia denominación 'TEX ARGENTA' vs 'TEX ARGENTINA'; doble cláusula 4.3",
    "dias_venc": 626,
    "meses_rest": 20.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "20/03/2026",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Verificar la razón social (ARGENTA/ARGENTINA); corregir la doble cl. 4.3; aclarar el inicio retroactivo.",
    "pen": "Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + ocupación U$S200/día."
  },
  {
    "n": "T.G Health S.R.L.",
    "cuit": "30-71927423-0",
    "tipo": "ANMAT",
    "canon": 1700000,
    "mon": "ARS",
    "m2": 18,
    "ubic": "1° Piso Unidad 3 - Pedro de Luján 3151/3181",
    "ini": "2026-04-01",
    "venc": "2028-03-31",
    "renov": true,
    "riesgo": "Bajo",
    "estado": "Vigente",
    "desact": false,
    "hall": "El más sólido: doble certificación notarial (Rosario + CABA); falta multa Art.1221; corrección manuscrita de domicilio no formalizada",
    "dias_venc": 657,
    "meses_rest": 21.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "20/03/2026",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Formalizar por adenda la corrección de domicilio; incorporar la multa del Art. 1221; archivar seguros.",
    "pen": "Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + ocupación U$S200/día. HALLAZGO: la cláusula NO incluye la multa del 10% del Art. 1221 (omitida respecto del modelo estándar)."
  },
  {
    "n": "Laboratorio Integrador de Soluciones Pharma S.A.",
    "cuit": "30-71747918-8",
    "tipo": "ANMAT",
    "canon": 1800000,
    "mon": "ARS",
    "m2": 18,
    "ubic": "1° Piso Unidad 5 - Pedro de Luján 3151/3181",
    "ini": "2026-06-01",
    "venc": "2028-05-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Contrato + Acuse con penalidades discrepantes (1 vs 2 cánones); cláusula de retención más garantista para el cliente",
    "dias_venc": 718,
    "meses_rest": 23.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "21/05/2026",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Resolver la discrepancia de penalidades contrato/acuse; archivar el certificado de firma del contrato.",
    "pen": "Contrato: 1 canon por cada 30 días omitidos (mín. 1, máx. 2 cánones) + multa Art. 1221 (10% saldo futuro) si no se cumple el preaviso + ocupación U$S200/día. Condiciones Generales (posteriores): mín. 2 meses — prevalecen."
  },
  {
    "n": "Nicolás Leonardo Cooperate Company S.A.S.",
    "cuit": "30-71929288-3",
    "tipo": "ANMAT",
    "canon": 1890000,
    "mon": "ARS",
    "m2": 18,
    "ubic": "1° Piso Unidad 4 - Pedro de Luján 3151/3181",
    "ini": "2026-06-01",
    "venc": "2027-05-31",
    "renov": true,
    "riesgo": "Medio",
    "estado": "Vigente",
    "desact": false,
    "hall": "Único a 12 meses; preaviso 30 días (vs 60); discrepancia S.A.A./S.A.S.; error geográfico 'Salta, Buenos Aires'; sin bonificación",
    "dias_venc": 352,
    "meses_rest": 11.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "21/05/2026",
    "plazo": "12 m",
    "preaviso": "30 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Gestionar la renovación antes del 30/04/2027; corregir el tipo societario y el domicilio «Salta, Buenos Aires».",
    "pen": "Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 1, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + ocupación U$S200/día. Condiciones Generales: mín. 2 meses."
  },
  {
    "n": "Bonfarto Salud S.A.",
    "cuit": "30-71784349-1",
    "tipo": "ANMAT",
    "canon": 2000000,
    "mon": "ARS",
    "m2": 25,
    "ubic": "1° Piso Unidad 12 - Pedro de Luján 3151/3181",
    "ini": "2026-04-01",
    "venc": "2028-03-31",
    "renov": true,
    "riesgo": "Alto",
    "estado": "Vigente",
    "desact": false,
    "hall": "Inicio retroactivo 43 días; adenda con fecha en blanco sin firmar; penalidad U$S100/día (vs U$S200); sin NOSIS",
    "dias_venc": 657,
    "meses_rest": 21.9,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "13/05/2026",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Regularizar la adenda sin firma/fecha; revisar la penalidad de U$S100/día; solicitar NOSIS.",
    "pen": "Indemnización sustitutiva: mín. 2, máx. 6 cánones + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros (declarada acumulable con la indemnización, con ejemplo numérico) + ocupación U$S100/día (único del grupo con U$S100 en vez de U$S200)."
  },
  {
    "n": "Lucas Formia / Cala Med Argentina S.R.L.",
    "cuit": "s/d",
    "tipo": "Cargas Generales",
    "canon": 775600,
    "mon": "ARS",
    "m2": null,
    "ubic": "Magaldi 1765 (racks)",
    "ini": null,
    "venc": null,
    "renov": false,
    "riesgo": "Alto",
    "estado": "Sin-Instrumento",
    "desact": false,
    "hall": "Solo presupuesto SIN firma, vencido 25/12/2025; CUIT del cliente = CUIT de VEROTIN (error material); sin contrato",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Negro",
    "semaforo_label": "Vencido / Sin instrumento",
    "firma": "s/firma",
    "plazo": "s/d",
    "preaviso": "s/d",
    "ajuste": "CEDOL trimestral",
    "reco": "Formalizar contrato firmado; corregir el CUIT (figura el de VEROTIN); anexar condiciones generales.",
    "pen": "No surge de la documentación (solo existe un presupuesto sin firma; no hay contrato ni cláusula de penalidad)."
  },
  {
    "n": "DIVANLITO S.A.C.I.Y.F.",
    "cuit": "30-53921802-2",
    "tipo": "Cargas Generales",
    "canon": 1950000,
    "mon": "ARS",
    "m2": 1134,
    "ubic": "Pedro de Luján 3159",
    "ini": "2023-01-01",
    "venc": "2026-12-31",
    "renov": true,
    "riesgo": "Bajo",
    "estado": "Renov-No-Instrumentada",
    "desact": true,
    "hall": "Contrato bien estructurado; renovó automáticamente 12/2024; canon base ene-2023 sin actualizar; sin póliza de seguro",
    "dias_venc": 201,
    "meses_rest": 6.7,
    "semaforo": "Verde",
    "semaforo_label": "> 90 días",
    "firma": "21/12/2022",
    "plazo": "24 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Documentar el canon vigente; exigir póliza de seguro; renegociar al renovar.",
    "pen": "Omisión de preaviso = equivalente a 60 días de almacenaje (indemnización sustitutiva); derecho de retención de mercadería ante deuda; interés punitorio 3× tasa activa BNA a 30 días."
  },
  {
    "n": "Impresiones Flexográficas S.R.L.",
    "cuit": "30-71580288-7",
    "tipo": "Cargas Generales",
    "canon": 78000,
    "mon": "ARS",
    "m2": null,
    "ubic": "Magaldi 1765",
    "ini": null,
    "venc": null,
    "renov": false,
    "riesgo": "Alto",
    "estado": "Incierto",
    "desact": true,
    "hall": "Relación A-0645 cerrada (retiro feb-2023); nueva propuesta A-0672 sin contrato firmado ni evidencia de operación; estado incierto",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Gris",
    "semaforo_label": "A revisar / Estado incierto",
    "firma": "s/contrato (A-0672)",
    "plazo": "6 m",
    "preaviso": "60 días",
    "ajuste": "CEDOL semestral",
    "reco": "Definir si el cliente está activo; formalizar contrato o archivar la relación.",
    "pen": "Según Condiciones Generales: 1 mes de alquiler por cada 30 días de preaviso omitido (mín. 2 meses); intereses moratorios 3× tasa activa BNA. (Sin contrato bilateral vigente para la etapa A-0672.)"
  },
  {
    "n": "ISOLTECH",
    "cuit": "s/d",
    "tipo": "Cargas Generales",
    "canon": null,
    "mon": "ARS",
    "m2": null,
    "ubic": "s/d",
    "ini": null,
    "venc": null,
    "renov": false,
    "riesgo": "Crítico",
    "estado": "Sin-Instrumento",
    "desact": false,
    "hall": "Carpeta SIN documentación contractual alguna; solo ficha técnica de producto; único indicio = carta de aumento de 2017",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Negro",
    "semaforo_label": "Vencido / Sin instrumento",
    "firma": "—",
    "plazo": "—",
    "preaviso": "—",
    "ajuste": "—",
    "reco": "Verificar si opera; formalizar o dar de baja; centralizar la documentación dispersa.",
    "pen": "No surge de la documentación (la carpeta no contiene instrumento contractual alguno)."
  },
  {
    "n": "NATAN (Wasser Natán Ezequiel)",
    "cuit": "20-33023871-2",
    "tipo": "Cargas Generales",
    "canon": null,
    "mon": "ARS",
    "m2": null,
    "ubic": "Magaldi 1765 / Luján 3169",
    "ini": null,
    "venc": null,
    "renov": false,
    "riesgo": "Crítico",
    "estado": "Incierto",
    "desact": true,
    "hall": "Relación 2016-2018 con retiro 2017 (sin firma); propuesta dic-2025 ilegible sin acuse; estado indeterminado",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Gris",
    "semaforo_label": "A revisar / Estado incierto",
    "firma": "03/11/2016",
    "plazo": "indet.",
    "preaviso": "60 días",
    "ajuste": "CEDOL",
    "reco": "Determinar el estado; formalizar nuevo contrato; liquidar formalmente la etapa 2016-2017.",
    "pen": "Condiciones Generales 2016: mín. 2 meses de alquiler si se omite el preaviso (60 días); intereses moratorios 2× tasa activa BNA (versión 2016, menos protectora que la actual de 3×)."
  },
  {
    "n": "Importadora Real S.R.L.",
    "cuit": "30-70926538-1",
    "tipo": "Cargas Generales",
    "canon": 1650000,
    "mon": "ARS",
    "m2": 100,
    "ubic": "Magaldi 1765",
    "ini": "2016-02-02",
    "venc": null,
    "renov": false,
    "riesgo": "Medio",
    "estado": "Vigente-Indet",
    "desact": false,
    "hall": "Propuesta A-0817 (2025) sin acuse firmado; plazo mínimo venció dic-2025; mail 2026 'dejan depósito ANMAT' sugiere baja no documentada",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Azul",
    "semaforo_label": "Vigente plazo indeterminado",
    "firma": "s/acuse (A-0817)",
    "plazo": "indet.",
    "preaviso": "60 días",
    "ajuste": "CEDOL trimestral",
    "reco": "Obtener acuse firmado de A-0817; verificar la baja del depósito ANMAT informada por mail.",
    "pen": "Condiciones Generales: 1 mes de alquiler por cada 30 días de preaviso omitido (mín. 2 meses); base de cálculo = mes de mayor valor del año anterior a la rescisión; mora automática sin interpelación."
  },
  {
    "n": "AVANTECNO S.A.",
    "cuit": "33-70718113-9",
    "tipo": "Cargas Generales",
    "canon": 3286400,
    "mon": "ARS",
    "m2": 200,
    "ubic": "Magaldi 1880",
    "ini": "2017-07-10",
    "venc": null,
    "renov": false,
    "riesgo": "Bajo",
    "estado": "Vigente-Indet",
    "desact": false,
    "hall": "Aceptación A-0816 firmada (2025); preaviso acumulado ~8 meses por antigüedad; discrepancia N° propuesta A-0815/A-0816",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Azul",
    "semaforo_label": "Vigente plazo indeterminado",
    "firma": "17/03/2025",
    "plazo": "indet.",
    "preaviso": "≈8 meses (acum.)",
    "ajuste": "CEDOL trimestral",
    "reco": "Corregir el N° de propuesta; formalizar acuerdo con fecha de inicio; verificar vigencia del poder.",
    "pen": "Condiciones Generales: 1 mes de alquiler por cada 30 días de preaviso omitido (mín. 2 meses); base = mes de mayor valor del año anterior; aplica también ante reducción de servicios ≥ 50%."
  },
  {
    "n": "Silica Networks Argentina S.A.",
    "cuit": "30-70719317-0",
    "tipo": "Cargas Generales",
    "canon": 372150,
    "mon": "ARS",
    "m2": 450,
    "ubic": "Pedro de Luján 3151/3181/3159",
    "ini": "2017-08-01",
    "venc": null,
    "renov": false,
    "riesgo": "Medio",
    "estado": "Vigente-Indet",
    "desact": true,
    "hall": "Propuesta vigente con firma = 2017 (tarifa desactualizada); A-0512 (2021) sin acuse; preaviso acumulado ~8 meses; representación a verificar",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Azul",
    "semaforo_label": "Vigente plazo indeterminado",
    "firma": "20/07/2017",
    "plazo": "indet.",
    "preaviso": "≈8 meses (acum.)",
    "ajuste": "CEDOL semestral",
    "reco": "Obtener acuse de A-0512; actualizar condiciones y tarifa; verificar la representación legal.",
    "pen": "Condiciones Generales: 1 mes de alquiler por cada 30 días de preaviso omitido (mín. 2 meses). (Preaviso acumulado ≈ 8 meses por antigüedad desde 2017.)"
  },
  {
    "n": "ELIT S.A. (+ ARG S.A. codeudora)",
    "cuit": "30-65165551-6",
    "tipo": "Cargas Generales",
    "canon": 26140,
    "mon": "USD",
    "m2": 2920,
    "ubic": "Pedro de Luján 3151/3181 / Magaldi",
    "ini": "2014-09-04",
    "venc": null,
    "renov": false,
    "riesgo": "Medio",
    "estado": "Vigente-Indet",
    "desact": false,
    "hall": "Acuerdo tripartito firmado (2024); tarifa USD aceptada solo por email sin instrumento formal; sin mecanismo de ajuste; preaviso acumulado ~11 meses",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Azul",
    "semaforo_label": "Vigente plazo indeterminado",
    "firma": "31/08/2024",
    "plazo": "indet.",
    "preaviso": "≈11 meses (acum.)",
    "ajuste": "s/mecanismo (USD)",
    "reco": "Adenda formal de tarifa en USD con firma; incorporar mecanismo de ajuste; consignar el CUIT de ARG S.A.",
    "pen": "Acuerdo 2024: indemnización equivalente al valor mensual del almacenaje por cada año de vigencia (desde 04/09/2014), mín. 2 meses de facturación; base = mayor valor mensual del año anterior. (Preaviso acumulado ≈ 11 meses.)"
  },
  {
    "n": "GEVECO S.A.",
    "cuit": "30-64560159-5",
    "tipo": "Cargas Generales",
    "canon": 24000,
    "mon": "USD",
    "m2": 3000,
    "ubic": "Magaldi 1880 / Luján 3159",
    "ini": "2023-08-10",
    "venc": null,
    "renov": true,
    "riesgo": "Crítico",
    "estado": "Rescindido",
    "desact": false,
    "hall": "RESCINDIDO 31/01/2026; penalidad U$S72.000 pagada; conflicto post-contractual: reparación racks U$S10.300 impaga, retención de 6 pallets, 3 CD sin respuesta (abr-2026)",
    "dias_venc": null,
    "meses_rest": null,
    "semaforo": "Negro",
    "semaforo_label": "Vencido / Sin instrumento",
    "firma": "10/08/2023",
    "plazo": "24 m",
    "preaviso": "90 días",
    "ajuste": "CEDOL/MEP condicionado",
    "reco": "Acción judicial: cobro de reparación de racks (U$S10.300) y venta de pallets retenidos; investigar el vínculo con CORVEN.",
    "pen": "Adenda I (cl. 2.3): esquema escalonado en USD según meses restantes. Rescindió con 12-10 meses restantes ⇒ penalidad de U$S72.000 (abonada según el Acta de Entrega). Mora: interés 2× tasa activa BNA (cl. 8.3)."
  }
];

/** Agregados canónicos de la auditoría (referencia/validación del tablero). */
export const AUDIT_AGGREGATES: ContractsAggregates = {
  "total": 45,
  "anmat": 35,
  "cg": 10,
  "activos": 42,
  "factArs": 49677060,
  "factUsd": 26140,
  "factArsAnual": 596124720,
  "factUsdAnual": 313680,
  "factArsDesact": 6522893,
  "nDesact": 19,
  "m2Total": 6843.97,
  "prox180": 8,
  "criticos": 7,
  "riesgos": {
    "Medio": 22,
    "Bajo": 5,
    "Alto": 11,
    "Crítico": 7
  },
  "semaforos": {
    "Verde": 32,
    "Amarillo": 2,
    "Naranja": 1,
    "Negro": 4,
    "Gris": 2,
    "Azul": 4
  },
  "estados": {
    "Vigente": 18,
    "En-Conflicto": 1,
    "Renov-No-Instrumentada": 16,
    "En-Litigio": 1,
    "Sin-Instrumento": 2,
    "Incierto": 2,
    "Vigente-Indet": 4,
    "Rescindido": 1
  }
};
