-- =========================================================================
-- 0076_contracts_audit_seed — Carga inicial de la cartera auditada (45 contratos)
-- =========================================================================
-- Acompaña a la migración 0076_crm_contracts.sql. Inserta las 45 relaciones
-- contractuales relevadas en la «Auditoría Contractual Integral» (corte
-- 13/06/2026) — Roadmap Fase 2 (carga inicial del MVP).
--
--   · public_id se asigna por trigger (CTR-AAAA-NNNN); id por gen_random_uuid().
--   · Idempotente: sólo inserta si public.contracts está vacía.
--   · client_id queda NULL (vínculo con Clientify en Fase 5).
--   · NO aplicado a producción desde esta sesión (esperar aprobación).
-- =========================================================================

insert into public.contracts (
  razon_social, cuit, tipo, canon, moneda, m2, ubicacion, fecha_inicio, fecha_fin,
  renovacion_automatica, riesgo, estado, canon_desactualizado, ajuste, ajuste_indice,
  ajuste_frecuencia, fecha_firma, plazo_meses, preaviso_dias, semaforo, hallazgos,
  recomendacion, penalidad
)
select
  razon_social, cuit, tipo, canon, moneda, m2, ubicacion,
  fecha_inicio::date, fecha_fin::date, renovacion_automatica, riesgo, estado,
  canon_desactualizado, ajuste, ajuste_indice, ajuste_frecuencia,
  fecha_firma::date, plazo_meses, preaviso_dias, semaforo, hallazgos,
  recomendacion, penalidad
from (values
  ('DEO Distribuidora de Equipos Odontológicos S.A.', '30-71911511-6', 'ANMAT'::contract_tipo_t, 4000000, 'ARS'::contract_moneda_t, 50, 'Osvaldo Cruz 3201 / Magaldi 1765', '2026-06-01', '2028-05-31', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2026-05-21', 24, 60, 'Verde'::contract_semaforo_t, 'Ajuste semestral (resto trimestral); acuse firmado 02-08-26 posterior al inicio; dualidad normativa contrato/condiciones', 'Unificar contrato y condiciones; pasar el ajuste a trimestral; regularizar la fecha del acuse.', 'Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día.'),
  ('PEGHI Commerce S.A.S.', '30-71925571-6', 'ANMAT'::contract_tipo_t, 1500000, 'ARS'::contract_moneda_t, 17, 'Osvaldo Cruz 3201 / Magaldi 1765', '2026-02-01', '2027-01-31', true, 'Bajo'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-02-04', 12, 30, 'Verde'::contract_semaforo_t, 'Firma digital certificada; omisión de ''m²'' en cl.1.1', 'Corregir la omisión de «m²» en cl. 1.1; iniciar la renovación anticipadamente.', 'Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 1, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + cláusula penal 2 cánones + 10% + ocupación U$S200/día.'),
  ('RO Latin Medical Argentina S.R.L.', '30-71899606-2', 'ANMAT'::contract_tipo_t, 1350000, 'ARS'::contract_moneda_t, 38, 'Nave 5 - Osvaldo Cruz 3201 / Magaldi 1765', '2026-01-01', '2027-12-31', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-01-08', 24, 90, 'Verde'::contract_semaforo_t, 'Contrato bajo razón social anterior (cambio de denominación); régimen de responsabilidad Art.1376 más gravoso; penalidades reducidas', 'Adenda urgente por cambio de denominación social; alinear el régimen de responsabilidad y elevar el tope de penalidades.', 'Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 2, máx. 3 cánones) + cláusula penal 2 cánones + 10% + ocupación U$S200/día. NO incluye la multa del 10% del Art. 1221 (penalidad reducida vs. el modelo estándar).'),
  ('Vitalis Pharma S.A.', '30-71916753-1', 'ANMAT'::contract_tipo_t, 1890000, 'ARS'::contract_moneda_t, 65, 'Pedro de Luján 3151/3181', '2025-12-01', '2027-11-30', true, 'Alto'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-12-10', 24, 60, 'Verde'::contract_semaforo_t, 'ERROR tipográfico vencimiento ''207''; doble firmante sin personería; propuesta posterior al contrato; domicilios contradictorios', 'ADENDA URGENTE: corregir el año de vencimiento «207»→2027; acreditar personería del firmante; unificar domicilios.', 'Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día.'),
  ('PADECO S.A.', '30-70828842-6', 'ANMAT'::contract_tipo_t, 792000, 'ARS'::contract_moneda_t, 17, 'Unidad 9 - Osvaldo Cruz 3201 / Magaldi 1765', '2025-11-01', '2026-10-31', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-10-28', 12, 30, 'Verde'::contract_semaforo_t, 'Próximo a vencer; sin mínimo en indemnización sustitutiva', 'Iniciar la renovación ya (vence 31/10/2026); fijar un mínimo de indemnización sustitutiva.', 'Indemnización sustitutiva: 1 canon por cada 30 días omitidos (sin mínimo expreso, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + cláusula penal 2 cánones + 10% + ocupación U$S200/día. (Laguna: no fija piso de indemnización.)'),
  ('LION BUSINES S.R.L.', '30-71903156-7', 'ANMAT'::contract_tipo_t, 765000, 'ARS'::contract_moneda_t, 56.97, 'Unidad 7 - Osvaldo Cruz 3201 / Magaldi 1765', '2025-08-01', '2027-07-31', true, 'Alto'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-08-05', 24, 60, 'Verde'::contract_semaforo_t, 'Adenda amplió superficie +42% SIN modificar canon; dos versiones de adenda; razón social con posible error', 'URGENTE: adenda que fije el canon de los 56,97 m²; unificar las dos versiones de la adenda.', 'Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día.'),
  ('Business For Pharma S.R.L.', '30-71871534-9', 'ANMAT'::contract_tipo_t, 1000000, 'ARS'::contract_moneda_t, 38, 'Unidad 1 - Osvaldo Cruz 3201 / Magaldi 1765', '2025-07-01', '2027-06-30', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-07-14', 24, 60, 'Verde'::contract_semaforo_t, 'Canon duplicado por adenda el mismo día; cl.2.1 renovación contradictoria', 'Corregir la contradicción de la cl. 2.1 (renovación); jerarquizar contrato vs. condiciones generales.', 'Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día.'),
  ('Korean Skin S.R.L.', '30-71860717-1', 'ANMAT'::contract_tipo_t, 400000, 'ARS'::contract_moneda_t, 20, 'Unidad 6 - Magaldi 1765', '2025-02-01', '2027-01-31', true, 'Medio'::contract_riesgo_t, 'Vigente', true, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-02-11', 24, 60, 'Verde'::contract_semaforo_t, 'Canon feb-2025 sin actualización CEDOL documentada; renovación hasta 4 períodos (compromiso 10 años)', 'Documentar los ajustes CEDOL aplicados; cuantificar la indemnización por rescisión.', 'El contrato remite a los arts. 1221/1199/2587-2593 CCyCN; las Condiciones Generales cuantifican: 1 mes de alquiler por cada 30 días omitidos (mín. 2 meses) + ocupación U$S200/día. (No cuantificada en el cuerpo del contrato.)'),
  ('ROBI Insumos Médicos S.R.L.', '30-71878091-4', 'ANMAT'::contract_tipo_t, 1300000, 'ARS'::contract_moneda_t, 17, 'Unidad 7 - Osvaldo Cruz 3201 / Magaldi 1765', '2026-01-01', '2027-12-31', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-01-06', 24, 60, 'Verde'::contract_semaforo_t, 'Firma electrónica certificada; condiciones generales con domicilio en blanco; firmadas antes que el contrato', 'Completar el domicilio en las condiciones generales; alinear fechas de firma.', 'Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día.'),
  ('Silvia Noemí Willging', '27-13782891-5', 'ANMAT'::contract_tipo_t, 1600000, 'ARS'::contract_moneda_t, 70, 'Nave 3 Unidad 5 - Osvaldo Cruz 3201 / Magaldi 1765', '2025-11-01', '2027-10-31', true, 'Alto'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-10-30', 24, 60, 'Verde'::contract_semaforo_t, 'Persona física sin garantías; domicilio en La Pampa; hash de certificación inválido (string vacío)', 'Exigir garantía/fianza (persona física, domicilio en el interior); reemitir condiciones con hash de firma válido.', 'Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día.'),
  ('Medical Inputs S.R.L.', '30-71860398-2', 'ANMAT'::contract_tipo_t, 500000, 'ARS'::contract_moneda_t, 30, 'Unidad 2 - Osvaldo Cruz 3201 / Magaldi 1765', '2024-09-01', '2026-08-31', true, 'Crítico'::contract_riesgo_t, 'Vigente', true, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2024-08-28', 24, 60, 'Amarillo'::contract_semaforo_t, 'URGENTE: preaviso de no renovación vence 02/07/2026; canon base sep-2024 sin actualizar (6 ajustes pendientes)', 'ACCIÓN ANTES DEL 02/07/2026 (preaviso de no renovación); actualizar el canon (6 ajustes pendientes).', 'El contrato remite a los arts. 1221/1199/2587-2593 CCyCN; Condiciones Generales: 1 mes de alquiler por cada 30 días omitidos (mín. 2 meses) + ocupación U$S200/día.'),
  ('Migliore S.R.L.', '30-71475048-4', 'ANMAT'::contract_tipo_t, 900000, 'ARS'::contract_moneda_t, 25, 'Unidad 6 PB - Osvaldo Cruz 3201 / Magaldi 1765', '2025-09-01', '2027-08-31', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-09-19', 24, 60, 'Verde'::contract_semaforo_t, 'Condiciones firmadas 23 días antes del contrato; posible superposición de Unidad 6 con Korean Skin', 'Verificar superposición de la Unidad 6 con Korean Skin; reconocer la retroactividad por adenda.', 'Indemnización sustitutiva de preaviso: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros desde la notificación hasta el vencimiento + cláusula penal 2 cánones + 10% por incumplimiento + ocupación extemporánea U$S200/día.'),
  ('Bio Analítica Argentina S.A.', '30-70753876-3', 'ANMAT'::contract_tipo_t, 2525696, 'ARS'::contract_moneda_t, 50, 'Nave 3 Unidad 4 - Osvaldo Cruz 3201 / Magaldi 1765', '2025-08-01', '2026-10-31', true, 'Crítico'::contract_riesgo_t, 'En-Conflicto', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-08-06', 24, 60, 'Naranja'::contract_semaforo_t, 'Contrato RESCINDIDO por mora (CD abr-2026, deuda ~$11M); acuerdo informal de regularización pago adelantado may-oct 2026 SIN nuevo instrumento firmado', 'URGENTE: formalizar el acuerdo de mayo 2026 como nuevo instrumento; acreditar el cobro de los cheques.', 'Omisión de preaviso = indemnización sustitutiva de 2 cánones; cláusula penal por incumplimiento 2 cánones + 10%; ocupación U$S200/día; mora en pago: interés punitorio 3× tasa activa BNA + derecho de retención de mercadería.'),
  ('MEDIMPO S.R.L.', '30-71849548-9', 'ANMAT'::contract_tipo_t, 1000000, 'ARS'::contract_moneda_t, 50, 'Magaldi 1765 (UF 3.1/3.2)', '2024-03-02', '2028-03-01', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2024-05-03', 24, 60, 'Verde'::contract_semaforo_t, 'Renovación automática operada (01/03/2026) no documentada; canon base mar-2024 sin actualizar; hasta 4 períodos', 'Documentar la renovación de 03/2026; actualizar el canon; verificar habilitaciones por unidad funcional.', 'Omisión de preaviso = mín. 2 meses de alquiler (1 mes por cada 30 días); ocupación U$S200/día; mora: 3× tasa activa BNA + retención; incumplimiento: cánones pendientes hasta fin de plazo + U$S200/día.'),
  ('INGEMED S.A.', '30-71245879-4', 'ANMAT'::contract_tipo_t, 162000, 'ARS'::contract_moneda_t, 10, 'Osvaldo Cruz 3201 / Magaldi 1765', '2024-01-02', '2028-01-01', true, 'Bajo'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2023-12-26', 24, 60, 'Verde'::contract_semaforo_t, 'Contrato legalizado ante escribana (el más robusto); CUIT VEROTIN mal tipeado en cl.4.3; canon base ene-2024 sin actualizar', 'Corregir el CUIT de VEROTIN en cl. 4.3; documentar la renovación; incorporar el cargo de desconsolidado.', 'Omisión de preaviso = mín. 2 meses de alquiler; ocupación U$S200/día; mora: 3× tasa activa BNA + retención de mercadería.'),
  ('Medicina del Plata S.R.L.', '30-71822590-2', 'ANMAT'::contract_tipo_t, 616200, 'ARS'::contract_moneda_t, 70, 'Depósito 5 - Osvaldo Cruz 3201 / Magaldi 1765', '2023-11-13', '2027-11-12', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2023-11-01', 24, 60, 'Verde'::contract_semaforo_t, 'Adenda abr-2025 solo en Google Doc sin firma; canon base nov-2023 sin actualizar', 'Obtener la adenda firmada (hoy solo Google Doc); anexar tarifas de servicios; documentar la renovación.', 'Omisión de preaviso = mín. 2 meses de alquiler; ocupación U$S200/día; mora: 3× tasa activa BNA + retención de mercadería.'),
  ('WINTRADE S.A.', '30-71466762-5', 'ANMAT'::contract_tipo_t, 349440, 'ARS'::contract_moneda_t, 60, 'Osvaldo Cruz 3201 / Magaldi 1765', '2023-08-15', '2027-08-14', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2023-08-17', 24, 60, 'Verde'::contract_semaforo_t, 'Descuento 30% condicionado a pago semestral sin verificación; ajuste semestral; canon base ago-2023', 'Cláusula de reversión de precio si no se paga el semestre adelantado; migrar a ajuste trimestral.', 'Omisión de preaviso = mín. 2 meses de alquiler; ocupación U$S200/día; mora: 3× tasa activa BNA + retención de mercadería.'),
  ('Q-ADVICE S.A.S.', '30-71710748-5', 'ANMAT'::contract_tipo_t, 200000, 'ARS'::contract_moneda_t, 30, 'Pedro de Luján 3151/3181', '2023-08-01', '2027-07-31', true, 'Alto'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2023-08-01', 24, 60, 'Verde'::contract_semaforo_t, 'CUIT al pie ≠ encabezado; doble cláusula 4.3; contradicción provisión de pallets; canon base ago-2023', 'Corregir el CUIT del cliente; verificar la habilitación ANMAT del depósito de Luján; aclarar provisión de pallets.', 'Omisión de preaviso = mín. 2 meses de alquiler; ocupación U$S200/día; mora: 3× tasa activa BNA + retención de mercadería.'),
  ('Panalab Argentina S.A.', '30-65812709-4', 'ANMAT'::contract_tipo_t, 161100, 'ARS'::contract_moneda_t, 12, 'Osvaldo Cruz 3201 / Magaldi 1765 (depósito + oficina)', '2023-01-18', '2026-12-31', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'IPCBA semestral', 'IPCBA', 'semestral'::contract_ajuste_frecuencia_t, '2023-01-18', 24, 60, 'Verde'::contract_semaforo_t, 'Instrumento ''Carta Oferta'' atípico; ajuste IPCBA (no CEDOL); oficina sin contrato autónomo; superficie depósito no consignada', 'Regularizar la oficina con contrato propio; unificar el índice de ajuste; consignar la superficie del depósito.', 'Carta Oferta (locación): al cursar el preaviso, el cliente abona 2 cánones mensuales; mora en devolución del depósito U$S100/día. (Cl. 1.4 excluye indemnizaciones adicionales — interpretar armónicamente con 1.3.)'),
  ('KODENT S.A.', '30-71005846-2', 'ANMAT'::contract_tipo_t, 2603442, 'ARS'::contract_moneda_t, 37, 'Depósitos 5 y 8 - Osvaldo Cruz 3201 / Magaldi 1765', '2022-11-15', '2026-11-14', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', false, 'CEDOL (de facto trimestral)', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2022-11-14', 24, 60, 'Verde'::contract_semaforo_t, 'Único con planilla de ajustes (mejor gestionado); frecuencia cambiada de facto semestral→trimestral sin adenda; error en 1er ajuste', 'Adenda que formalice la frecuencia trimestral y el canon vigente; subsanar el error del 1er ajuste.', 'Falta de preaviso (60 días) = equivalente a los días de preaviso omitidos; incumplimiento de uso (cl. 3.3): alquileres pendientes hasta fin de plazo + U$S50/día; mora en devolución al vencimiento U$S100/día.'),
  ('ELINTEC S.A.', '30-71422762-5', 'ANMAT'::contract_tipo_t, 60000, 'ARS'::contract_moneda_t, 16, 'Pedro de Luján 3151/3181', '2022-08-15', '2026-08-14', true, 'Alto'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2022-08-25', 12, 60, 'Amarillo'::contract_semaforo_t, '4 años sin actualización ni adenda; INCONSISTENCIA de dirección cl.1ª (Luján) vs cl.9ª (Magaldi) con riesgo ANMAT; canon base ago-2022', 'URGENTE: corregir la inconsistencia de dirección (Luján vs. Magaldi) por su impacto ANMAT; adenda con canon actualizado.', 'Falta de preaviso = equivalente a los días omitidos; incumplimiento de uso: alquileres pendientes + U$S100/día; mora en devolución al vencimiento U$S200/día.'),
  ('AMAOTO S.R.L.', '30-71682677-1', 'ANMAT'::contract_tipo_t, 65000, 'ARS'::contract_moneda_t, 17, 'Osvaldo Cruz 3201 / Magaldi 1765', '2022-04-01', '2028-03-31', true, 'Alto'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2022-03-29', 24, 60, 'Verde'::contract_semaforo_t, 'Venció 31/03/2026; renovación automática presunta no instrumentada; canon base $65.000 irreal; anexo de cubículos ene-2026 sin firmar', 'Firmar nuevo contrato/adenda con el canon real; instrumentar la eventual migración a cubículos.', 'Falta de preaviso = equivalente a los días omitidos; incumplimiento de uso: alquileres pendientes + U$S100/día; mora en devolución al vencimiento U$S200/día.'),
  ('Forever Living Products Argentina S.R.L.', '33-66345385-4', 'ANMAT'::contract_tipo_t, 303914, 'ARS'::contract_moneda_t, 65, 'Osvaldo Cruz 3201 / Magaldi 1765 (2 depósitos)', '2022-11-01', '2026-10-31', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2022-12-21', 24, 60, 'Verde'::contract_semaforo_t, 'Discordancia de CUIT entre documentos (33- vs 30-); deslinde 2021 sin firmante identificado; canon base nov-2022', 'Verificar y unificar el CUIT; completar el deslinde; documentar los ajustes.', 'Falta de preaviso = equivalente a los días omitidos; incumplimiento de uso: alquileres pendientes + U$S100/día; mora en devolución al vencimiento U$S200/día.'),
  ('Dana Yasmín Atena', '29-39428293-1', 'ANMAT'::contract_tipo_t, 127710, 'ARS'::contract_moneda_t, 17, 'Osvaldo Cruz 3201 / Magaldi 1765', '2023-02-01', '2027-01-31', true, 'Crítico'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2023-02-15', 12, 60, 'Verde'::contract_semaforo_t, 'ERROR tipográfico año de firma ''2323''; persona física por apoderada sin verificar poder; venció 31/01/2026 sin instrumento nuevo; canon base feb-2023', 'URGENTE: nuevo contrato que subsane el año «2323» y fije el canon; verificar el poder de la apoderada.', 'Falta de preaviso = equivalente a los días omitidos; incumplimiento de uso: alquileres pendientes + U$S100/día; mora en devolución al vencimiento U$S200/día.'),
  ('Royal Packs S.A.', '30-71690136-6', 'ANMAT'::contract_tipo_t, 3231200, 'ARS'::contract_moneda_t, 400, 'Nave II - Magaldi 1765', '2024-03-13', '2028-03-12', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2024-03-25', 24, 60, 'Verde'::contract_semaforo_t, 'Penalidad U$S200/día sin tope; propuesta decía ajuste semestral vs contrato trimestral; renovó automáticamente 03/2026', 'Tope de días para ocupación extemporánea (U$S200/día sin tope); unificar contrato + condiciones.', 'Indemnización por preaviso omitido = mín. 2 meses de alquiler (calculado sobre el mes de mayor valor del año anterior) + ocupación extemporánea U$S200/día; aplican arts. 1221/1199/2587-2593 CCyCN.'),
  ('TINU S.R.L.', '30-71547481-2', 'ANMAT'::contract_tipo_t, 39000, 'ARS'::contract_moneda_t, 17, 'Osvaldo Cruz 3201 / Magaldi 1765', '2020-10-01', '2026-09-30', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2020-10-01', 24, 60, 'Verde'::contract_semaforo_t, 'Sin tope de renovaciones; doble dirección; canon base 2020 ($39.000) sin historial de ajustes', 'Adenda con canon actualizado, dirección única y tope de renovaciones automáticas.', 'Preaviso de 60 días o pago sustitutivo; ocupación extemporánea U$S200/día; por incumplimiento de uso: cánones pendientes hasta fin de plazo + U$S100/día.'),
  ('Técnicas Mínimo Invasivas S.A.', '30-71138635-8', 'ANMAT'::contract_tipo_t, 143879, 'ARS'::contract_moneda_t, 50, 'Magaldi 1765', '2022-01-01', '2027-12-31', true, 'Medio'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2022-01-03', 36, 60, 'Verde'::contract_semaforo_t, 'Renovación 36m no formalizada (Google Doc sin firma); penalidad U$S100/día (más baja); canon base ene-2022', 'Formalizar la renovación con firma; documentar ajustes; elevar la penalidad a U$S200/día.', 'Preaviso de 60 días o pago sustitutivo (mín. 2 meses según Condiciones Generales); ocupación extemporánea U$S200/día; incumplimiento de uso: cánones pendientes + U$S100/día.'),
  ('Compañía de Higiene S.R.L.', '33-71228608-9', 'ANMAT'::contract_tipo_t, 72500, 'ARS'::contract_moneda_t, 50, 'Magaldi 1765', '2020-05-01', '2029-04-30', true, 'Alto'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2020-05-04', 36, 60, 'Verde'::contract_semaforo_t, 'Relación más antigua (2020); cl.2.1 sin plazo de preaviso legible; sin tope de renovaciones; canon base 2020 más desactualizado', 'Adenda: actualizar canon, fijar preaviso claro y tope de renovaciones; verificar el preaviso ya operado.', 'Preaviso de 60 días o equivalente dinerario; ocupación extemporánea U$S200/día; incumplimiento de uso: cánones pendientes hasta fin de plazo + U$S100/día.'),
  ('ULTRALINE S.A.', '30-68076098-1', 'ANMAT'::contract_tipo_t, 3970429, 'ARS'::contract_moneda_t, 530, 'Pedro de Luján 3159', '2023-10-01', '2026-09-30', true, 'Crítico'::contract_riesgo_t, 'En-Litigio', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2023-09-29', 36, 180, 'Negro'::contract_semaforo_t, 'Cliente bajo INTERVENCIÓN JUDICIAL; deuda impaga ~$30M (nov-dic 2024); derecho de retención ejercido; resolución judicial jul-2025', 'URGENTE (legal): ejecutar retención y cobro (~$30M); verificar la resolución judicial de jul-2025; tasar el stock.', 'Rescisión anticipada por el cliente: preaviso de 180 días corridos o pago sustitutivo; ocupación extemporánea U$S100/día; incumplimiento de uso: cánones pendientes + U$S100/día. (VEROTIN puede rescindir sin causa con 180 días.)'),
  ('NARENA S.R.L.', '30-71441661-4', 'ANMAT'::contract_tipo_t, 1700000, 'ARS'::contract_moneda_t, 18, '1° Piso Unidad 1 - Pedro de Luján 3151/3181', '2026-03-01', '2028-02-29', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-02-27', 24, 60, 'Verde'::contract_semaforo_t, 'Contrato firmado + adenda; bonif. extensible por demoras sin tope; firmante apoderada sin certificación notarial', 'Aclarar la modalidad de renovación; topear la bonificación por demoras de obra; archivar seguros.', 'Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + ocupación U$S200/día.'),
  ('TEX ARGENTA S.R.L.', '30-68030867-1', 'ANMAT'::contract_tipo_t, 1700000, 'ARS'::contract_moneda_t, 18, '1° Piso Unidad 2 - Pedro de Luján 3151/3181', '2026-03-01', '2028-02-29', true, 'Alto'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-03-20', 24, 60, 'Verde'::contract_semaforo_t, 'Inicio retroactivo 20 días sin contrato; discrepancia denominación ''TEX ARGENTA'' vs ''TEX ARGENTINA''; doble cláusula 4.3', 'Verificar la razón social (ARGENTA/ARGENTINA); corregir la doble cl. 4.3; aclarar el inicio retroactivo.', 'Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + ocupación U$S200/día.'),
  ('T.G Health S.R.L.', '30-71927423-0', 'ANMAT'::contract_tipo_t, 1700000, 'ARS'::contract_moneda_t, 18, '1° Piso Unidad 3 - Pedro de Luján 3151/3181', '2026-04-01', '2028-03-31', true, 'Bajo'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-03-20', 24, 60, 'Verde'::contract_semaforo_t, 'El más sólido: doble certificación notarial (Rosario + CABA); falta multa Art.1221; corrección manuscrita de domicilio no formalizada', 'Formalizar por adenda la corrección de domicilio; incorporar la multa del Art. 1221; archivar seguros.', 'Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 2, máx. 6 cánones) + ocupación U$S200/día. HALLAZGO: la cláusula NO incluye la multa del 10% del Art. 1221 (omitida respecto del modelo estándar).'),
  ('Laboratorio Integrador de Soluciones Pharma S.A.', '30-71747918-8', 'ANMAT'::contract_tipo_t, 1800000, 'ARS'::contract_moneda_t, 18, '1° Piso Unidad 5 - Pedro de Luján 3151/3181', '2026-06-01', '2028-05-31', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-05-21', 24, 60, 'Verde'::contract_semaforo_t, 'Contrato + Acuse con penalidades discrepantes (1 vs 2 cánones); cláusula de retención más garantista para el cliente', 'Resolver la discrepancia de penalidades contrato/acuse; archivar el certificado de firma del contrato.', 'Contrato: 1 canon por cada 30 días omitidos (mín. 1, máx. 2 cánones) + multa Art. 1221 (10% saldo futuro) si no se cumple el preaviso + ocupación U$S200/día. Condiciones Generales (posteriores): mín. 2 meses — prevalecen.'),
  ('Nicolás Leonardo Cooperate Company S.A.S.', '30-71929288-3', 'ANMAT'::contract_tipo_t, 1890000, 'ARS'::contract_moneda_t, 18, '1° Piso Unidad 4 - Pedro de Luján 3151/3181', '2026-06-01', '2027-05-31', true, 'Medio'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-05-21', 12, 30, 'Verde'::contract_semaforo_t, 'Único a 12 meses; preaviso 30 días (vs 60); discrepancia S.A.A./S.A.S.; error geográfico ''Salta, Buenos Aires''; sin bonificación', 'Gestionar la renovación antes del 30/04/2027; corregir el tipo societario y el domicilio «Salta, Buenos Aires».', 'Indemnización sustitutiva: 1 canon por cada 30 días omitidos (mín. 1, máx. 6 cánones) + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros + ocupación U$S200/día. Condiciones Generales: mín. 2 meses.'),
  ('Bonfarto Salud S.A.', '30-71784349-1', 'ANMAT'::contract_tipo_t, 2000000, 'ARS'::contract_moneda_t, 25, '1° Piso Unidad 12 - Pedro de Luján 3151/3181', '2026-04-01', '2028-03-31', true, 'Alto'::contract_riesgo_t, 'Vigente', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2026-05-13', 24, 60, 'Verde'::contract_semaforo_t, 'Inicio retroactivo 43 días; adenda con fecha en blanco sin firmar; penalidad U$S100/día (vs U$S200); sin NOSIS', 'Regularizar la adenda sin firma/fecha; revisar la penalidad de U$S100/día; solicitar NOSIS.', 'Indemnización sustitutiva: mín. 2, máx. 6 cánones + multa Art. 1221 CCyCN: 10% del saldo de cánones futuros (declarada acumulable con la indemnización, con ejemplo numérico) + ocupación U$S100/día (único del grupo con U$S100 en vez de U$S200).'),
  ('Lucas Formia / Cala Med Argentina S.R.L.', null, 'Cargas Generales'::contract_tipo_t, 775600, 'ARS'::contract_moneda_t, null, 'Magaldi 1765 (racks)', null, null, false, 'Alto'::contract_riesgo_t, 'Sin-Instrumento', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, null, null, null, 'Negro'::contract_semaforo_t, 'Solo presupuesto SIN firma, vencido 25/12/2025; CUIT del cliente = CUIT de VEROTIN (error material); sin contrato', 'Formalizar contrato firmado; corregir el CUIT (figura el de VEROTIN); anexar condiciones generales.', 'No surge de la documentación (solo existe un presupuesto sin firma; no hay contrato ni cláusula de penalidad).'),
  ('DIVANLITO S.A.C.I.Y.F.', '30-53921802-2', 'Cargas Generales'::contract_tipo_t, 1950000, 'ARS'::contract_moneda_t, 1134, 'Pedro de Luján 3159', '2023-01-01', '2026-12-31', true, 'Bajo'::contract_riesgo_t, 'Renov-No-Instrumentada', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2022-12-21', 24, 60, 'Verde'::contract_semaforo_t, 'Contrato bien estructurado; renovó automáticamente 12/2024; canon base ene-2023 sin actualizar; sin póliza de seguro', 'Documentar el canon vigente; exigir póliza de seguro; renegociar al renovar.', 'Omisión de preaviso = equivalente a 60 días de almacenaje (indemnización sustitutiva); derecho de retención de mercadería ante deuda; interés punitorio 3× tasa activa BNA a 30 días.'),
  ('Impresiones Flexográficas S.R.L.', '30-71580288-7', 'Cargas Generales'::contract_tipo_t, 78000, 'ARS'::contract_moneda_t, null, 'Magaldi 1765', null, null, false, 'Alto'::contract_riesgo_t, 'Incierto', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, null, 6, 60, 'Gris'::contract_semaforo_t, 'Relación A-0645 cerrada (retiro feb-2023); nueva propuesta A-0672 sin contrato firmado ni evidencia de operación; estado incierto', 'Definir si el cliente está activo; formalizar contrato o archivar la relación.', 'Según Condiciones Generales: 1 mes de alquiler por cada 30 días de preaviso omitido (mín. 2 meses); intereses moratorios 3× tasa activa BNA. (Sin contrato bilateral vigente para la etapa A-0672.)'),
  ('ISOLTECH', null, 'Cargas Generales'::contract_tipo_t, null, 'ARS'::contract_moneda_t, null, null, null, null, false, 'Crítico'::contract_riesgo_t, 'Sin-Instrumento', false, null, null, null::contract_ajuste_frecuencia_t, null, null, null, 'Negro'::contract_semaforo_t, 'Carpeta SIN documentación contractual alguna; solo ficha técnica de producto; único indicio = carta de aumento de 2017', 'Verificar si opera; formalizar o dar de baja; centralizar la documentación dispersa.', 'No surge de la documentación (la carpeta no contiene instrumento contractual alguno).'),
  ('NATAN (Wasser Natán Ezequiel)', '20-33023871-2', 'Cargas Generales'::contract_tipo_t, null, 'ARS'::contract_moneda_t, null, 'Magaldi 1765 / Luján 3169', null, null, false, 'Crítico'::contract_riesgo_t, 'Incierto', true, 'CEDOL', 'CEDOL', null::contract_ajuste_frecuencia_t, '2016-11-03', null, 60, 'Gris'::contract_semaforo_t, 'Relación 2016-2018 con retiro 2017 (sin firma); propuesta dic-2025 ilegible sin acuse; estado indeterminado', 'Determinar el estado; formalizar nuevo contrato; liquidar formalmente la etapa 2016-2017.', 'Condiciones Generales 2016: mín. 2 meses de alquiler si se omite el preaviso (60 días); intereses moratorios 2× tasa activa BNA (versión 2016, menos protectora que la actual de 3×).'),
  ('Importadora Real S.R.L.', '30-70926538-1', 'Cargas Generales'::contract_tipo_t, 1650000, 'ARS'::contract_moneda_t, 100, 'Magaldi 1765', '2016-02-02', null, false, 'Medio'::contract_riesgo_t, 'Vigente-Indet', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, null, null, 60, 'Azul'::contract_semaforo_t, 'Propuesta A-0817 (2025) sin acuse firmado; plazo mínimo venció dic-2025; mail 2026 ''dejan depósito ANMAT'' sugiere baja no documentada', 'Obtener acuse firmado de A-0817; verificar la baja del depósito ANMAT informada por mail.', 'Condiciones Generales: 1 mes de alquiler por cada 30 días de preaviso omitido (mín. 2 meses); base de cálculo = mes de mayor valor del año anterior a la rescisión; mora automática sin interpelación.'),
  ('AVANTECNO S.A.', '33-70718113-9', 'Cargas Generales'::contract_tipo_t, 3286400, 'ARS'::contract_moneda_t, 200, 'Magaldi 1880', '2017-07-10', null, false, 'Bajo'::contract_riesgo_t, 'Vigente-Indet', false, 'CEDOL trimestral', 'CEDOL', 'trimestral'::contract_ajuste_frecuencia_t, '2025-03-17', null, null, 'Azul'::contract_semaforo_t, 'Aceptación A-0816 firmada (2025); preaviso acumulado ~8 meses por antigüedad; discrepancia N° propuesta A-0815/A-0816', 'Corregir el N° de propuesta; formalizar acuerdo con fecha de inicio; verificar vigencia del poder.', 'Condiciones Generales: 1 mes de alquiler por cada 30 días de preaviso omitido (mín. 2 meses); base = mes de mayor valor del año anterior; aplica también ante reducción de servicios ≥ 50%.'),
  ('Silica Networks Argentina S.A.', '30-70719317-0', 'Cargas Generales'::contract_tipo_t, 372150, 'ARS'::contract_moneda_t, 450, 'Pedro de Luján 3151/3181/3159', '2017-08-01', null, false, 'Medio'::contract_riesgo_t, 'Vigente-Indet', true, 'CEDOL semestral', 'CEDOL', 'semestral'::contract_ajuste_frecuencia_t, '2017-07-20', null, null, 'Azul'::contract_semaforo_t, 'Propuesta vigente con firma = 2017 (tarifa desactualizada); A-0512 (2021) sin acuse; preaviso acumulado ~8 meses; representación a verificar', 'Obtener acuse de A-0512; actualizar condiciones y tarifa; verificar la representación legal.', 'Condiciones Generales: 1 mes de alquiler por cada 30 días de preaviso omitido (mín. 2 meses). (Preaviso acumulado ≈ 8 meses por antigüedad desde 2017.)'),
  ('ELIT S.A. (+ ARG S.A. codeudora)', '30-65165551-6', 'Cargas Generales'::contract_tipo_t, 26140, 'USD'::contract_moneda_t, 2920, 'Pedro de Luján 3151/3181 / Magaldi', '2014-09-04', null, false, 'Medio'::contract_riesgo_t, 'Vigente-Indet', false, 's/mecanismo (USD)', 's/mecanismo', null::contract_ajuste_frecuencia_t, '2024-08-31', null, null, 'Azul'::contract_semaforo_t, 'Acuerdo tripartito firmado (2024); tarifa USD aceptada solo por email sin instrumento formal; sin mecanismo de ajuste; preaviso acumulado ~11 meses', 'Adenda formal de tarifa en USD con firma; incorporar mecanismo de ajuste; consignar el CUIT de ARG S.A.', 'Acuerdo 2024: indemnización equivalente al valor mensual del almacenaje por cada año de vigencia (desde 04/09/2014), mín. 2 meses de facturación; base = mayor valor mensual del año anterior. (Preaviso acumulado ≈ 11 meses.)'),
  ('GEVECO S.A.', '30-64560159-5', 'Cargas Generales'::contract_tipo_t, 24000, 'USD'::contract_moneda_t, 3000, 'Magaldi 1880 / Luján 3159', '2023-08-10', null, true, 'Crítico'::contract_riesgo_t, 'Rescindido', false, 'CEDOL/MEP condicionado', 'CEDOL/MEP', 'condicionado'::contract_ajuste_frecuencia_t, '2023-08-10', 24, 90, 'Negro'::contract_semaforo_t, 'RESCINDIDO 31/01/2026; penalidad U$S72.000 pagada; conflicto post-contractual: reparación racks U$S10.300 impaga, retención de 6 pallets, 3 CD sin respuesta (abr-2026)', 'Acción judicial: cobro de reparación de racks (U$S10.300) y venta de pallets retenidos; investigar el vínculo con CORVEN.', 'Adenda I (cl. 2.3): esquema escalonado en USD según meses restantes. Rescindió con 12-10 meses restantes ⇒ penalidad de U$S72.000 (abonada según el Acta de Entrega). Mora: interés 2× tasa activa BNA (cl. 8.3).')
) as v(
  razon_social, cuit, tipo, canon, moneda, m2, ubicacion, fecha_inicio, fecha_fin,
  renovacion_automatica, riesgo, estado, canon_desactualizado, ajuste, ajuste_indice,
  ajuste_frecuencia, fecha_firma, plazo_meses, preaviso_dias, semaforo, hallazgos,
  recomendacion, penalidad
)
where not exists (select 1 from public.contracts);

-- Verificación: select count(*) from public.contracts;  -- 45
