-- CRM360 · P1 · E1 — Seed de crm_units desde los mapas (lujan3159-map / magaldi1765-map).
-- Estado inicial = relevamiento físico 2026-06-04. Mapeo:
--   disponible→disponible · ocupado→ocupada · parcial→disponible (tiene m² libre)
--   interno→bloqueada · na (servicio/maniobra/pública)→no_comercializable
-- Idempotente: on conflict (site, unit_code) do nothing. Requiere 0066. NO aplicado a prod.

insert into public.crm_units (site, unit_code, name, tipo, category, floor, m2, state, ocupado_por, nota) values
-- ── PEDRO LUJÁN 3159 · sectores ──────────────────────────────────────────────
('PEDRO_LUJAN_3159','PB1','Depósito PB1','sector','general','PB',805,'disponible','Avantecno','parcial: 24 racks selectivos en uso; piso y 410 penetrables disponibles'),
('PEDRO_LUJAN_3159','PB2','Depósito PB2','sector','general','PB',997,'disponible',null,null),
('PEDRO_LUJAN_3159','PB3','Depósito PB3','sector','general','PB',500,'disponible','Divanlito','parcial ~50/50 a confirmar'),
('PEDRO_LUJAN_3159','PB4','Depósito PB4','sector','general','PB',300,'ocupada','Silica Networks',null),
('PEDRO_LUJAN_3159','PB5','Depósito PB5','sector','general','PB',970,'ocupada','Divanlito',null),
('PEDRO_LUJAN_3159','PB6','Depósito PB6','sector','general','PB',506,'disponible','Clientes varios','parcial ~30% ocupado / 354 m² disponibles'),
('PEDRO_LUJAN_3159','PB7','Depósito PB7','sector','general','PB',300,'ocupada','Silica Networks',null),
('PEDRO_LUJAN_3159','PB8','Depósito PB8','sector','general','PB',806,'disponible',null,null),
('PEDRO_LUJAN_3159','PB10','Depósito PB10','sector','anmat','PB',16,'ocupada','Elintec',null),
('PEDRO_LUJAN_3159','PB11','Depósito PB11','sector','anmat','PB',12,'ocupada','Cala Med',null),
('PEDRO_LUJAN_3159','PB15','Depósito PB15','sector','anmat','PB',30,'ocupada','Q-Advice',null),
('PEDRO_LUJAN_3159','PA1','Planta Alta 1 (PA1)','sector','general','P1',100,'ocupada','Avantecno',null),
('PEDRO_LUJAN_3159','PA2','Planta Alta 2 (PA2)','sector','anmat','P1',70,'ocupada','Vitalis Pharma',null),
-- ── PEDRO LUJÁN 3159 · cubículos ANMAT 1º piso (PA3+PA7) ─────────────────────
('PEDRO_LUJAN_3159','PA3+PA7-C01','Cubículo C01 (1ºP)','cubiculo','anmat','P1',18,'ocupada','Narena SRL',null),
('PEDRO_LUJAN_3159','PA3+PA7-C02','Cubículo C02 (1ºP)','cubiculo','anmat','P1',18,'ocupada','Tex Argenta SRL',null),
('PEDRO_LUJAN_3159','PA3+PA7-C03','Cubículo C03 (1ºP)','cubiculo','anmat','P1',18,'ocupada','T.G. Health SRL',null),
('PEDRO_LUJAN_3159','PA3+PA7-C04','Cubículo C04 (1ºP)','cubiculo','anmat','P1',18,'ocupada','Laboratorios Integrador',null),
('PEDRO_LUJAN_3159','PA3+PA7-C05','Cubículo C05 (1ºP)','cubiculo','anmat','P1',18,'ocupada','Nicolas Leonardo Company',null),
('PEDRO_LUJAN_3159','PA3+PA7-C06','Cubículo C06 (1ºP)','cubiculo','anmat','P1',18,'disponible',null,null),
('PEDRO_LUJAN_3159','PA3+PA7-C07','Cubículo C07 (1ºP)','cubiculo','anmat','P1',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA3+PA7-C08','Cubículo C08 (1ºP)','cubiculo','anmat','P1',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA3+PA7-C09','Cubículo C09 (1ºP)','cubiculo','anmat','P1',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA3+PA7-C10','Cubículo C10 (1ºP)','cubiculo','anmat','P1',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA3+PA7-C11','Cubículo C11 (1ºP)','cubiculo','anmat','P1',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA3+PA7-C12','Cubículo C12 (1ºP)','cubiculo','anmat','P1',25,'ocupada','Bonfarto Salud SA',null),
-- ── PEDRO LUJÁN 3159 · cubículos ANMAT 2º piso (PA4-PA5) — todos disponibles ──
('PEDRO_LUJAN_3159','PA4-PA5-C01','Cubículo C01 (2ºP)','cubiculo','anmat','P2',18,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C02','Cubículo C02 (2ºP)','cubiculo','anmat','P2',18,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C03','Cubículo C03 (2ºP)','cubiculo','anmat','P2',18,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C04','Cubículo C04 (2ºP)','cubiculo','anmat','P2',18,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C05','Cubículo C05 (2ºP)','cubiculo','anmat','P2',18,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C06','Cubículo C06 (2ºP)','cubiculo','anmat','P2',18,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C07','Cubículo C07 (2ºP)','cubiculo','anmat','P2',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C08','Cubículo C08 (2ºP)','cubiculo','anmat','P2',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C09','Cubículo C09 (2ºP)','cubiculo','anmat','P2',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C10','Cubículo C10 (2ºP)','cubiculo','anmat','P2',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C11','Cubículo C11 (2ºP)','cubiculo','anmat','P2',25,'disponible',null,null),
('PEDRO_LUJAN_3159','PA4-PA5-C12','Cubículo C12 (2ºP)','cubiculo','anmat','P2',25,'disponible',null,null),
-- ── MAGALDI 1765 · Planta Alta · oficinas/coworking ─────────────────────────
('MAGALDI_1765','OF-PA1','OF PA1','oficina','oficinas','PA',10,'disponible',null,'Coworking · oficina vendible'),
('MAGALDI_1765','OF-PA2','OF PA2','oficina','oficinas','PA',10,'disponible',null,'Coworking · oficina vendible'),
('MAGALDI_1765','OF-PA3','OF PA3','oficina','oficinas','PA',15,'disponible',null,'Coworking · oficina vendible'),
('MAGALDI_1765','OF-PA4','OF PA4','oficina','oficinas','PA',15,'disponible',null,'Coworking · oficina vendible'),
('MAGALDI_1765','CWP','Coworking Premium','coworking','oficinas','PA',null,'disponible',null,'11 islas · 56 puestos · 100% disponible (granularidad por isla = futuro)'),
('MAGALDI_1765','CEO','CEO','oficina','oficinas','PA',null,'bloqueada',null,'uso interno'),
('MAGALDI_1765','GER','Gerencia Comercial','oficina','oficinas','PA',null,'bloqueada',null,'uso interno'),
('MAGALDI_1765','DIROP','Dirección Operativa','oficina','oficinas','PA',null,'bloqueada',null,'uso interno'),
('MAGALDI_1765','CONF','Sala de Conferencias','oficina','oficinas','PA',null,'bloqueada',null,'uso interno'),
('MAGALDI_1765','ASIST','Of. Asistencia Ejecutiva','oficina','oficinas','PA',null,'bloqueada',null,'uso interno'),
('MAGALDI_1765','ARCH','Sala Archivo Documentación','oficina','oficinas','PA',null,'bloqueada',null,'uso interno'),
('MAGALDI_1765','CCOW','Comedor Coworking','servicio',null,'PA',null,'no_comercializable',null,null),
('MAGALDI_1765','VEST','Comedor / Vestuarios / Escalera','servicio',null,'PA',null,'no_comercializable',null,null),
-- ── MAGALDI 1765 · Planta Baja · Cargas Generales ───────────────────────────
('MAGALDI_1765','PB1','Depósito PB1','sector','general','PB',900,'ocupada',null,'400 posiciones racks selectivos'),
('MAGALDI_1765','PB2','Depósito PB2','sector','general','PB',300,'ocupada',null,'150 m² 1er piso + 150 altillo'),
('MAGALDI_1765','PB3','Depósito PB3','sector','general','PB',100,'ocupada',null,null),
('MAGALDI_1765','PB4','Depósito PB4','sector','general','PB',1000,'ocupada',null,'564 posiciones racks selectivos'),
('MAGALDI_1765','PB5','Depósito PB5','sector','general','PB',100,'ocupada',null,null),
('MAGALDI_1765','PB5A','PB5A (Tinglado)','sector','general','PB',120,'ocupada',null,null),
-- ── MAGALDI 1765 · Planta Baja · ANMAT (PB6–PB32) ───────────────────────────
('MAGALDI_1765','PB6','Depósito PB6','sector','anmat','PB',400,'ocupada',null,null),
('MAGALDI_1765','PB7','ANMAT PB7','sector','anmat','PB',70,'ocupada',null,null),
('MAGALDI_1765','PB8','ANMAT PB8','sector','anmat','PB',50,'ocupada',null,null),
('MAGALDI_1765','PB9','ANMAT PB9','sector','anmat','PB',50,'ocupada',null,null),
('MAGALDI_1765','PB10','ANMAT PB10','sector','anmat','PB',50,'ocupada',null,null),
('MAGALDI_1765','PB11','ANMAT PB11','sector','anmat','PB',50,'ocupada',null,null),
('MAGALDI_1765','PB12','ANMAT PB12','sector','anmat','PB',70,'ocupada',null,null),
('MAGALDI_1765','PB13','PB13','sector','anmat','PB',30,'ocupada',null,null),
('MAGALDI_1765','PB14','PB14','sector','anmat','PB',15,'ocupada',null,null),
('MAGALDI_1765','PB15','PB15','sector','anmat','PB',17,'ocupada',null,null),
('MAGALDI_1765','PB16','PB16','sector','anmat','PB',17,'ocupada',null,null),
('MAGALDI_1765','PB17','PB17','sector','anmat','PB',25,'ocupada',null,null),
('MAGALDI_1765','PB18','PB18','sector','anmat','PB',30,'ocupada',null,null),
('MAGALDI_1765','PB19','PB19','sector','anmat','PB',17,'ocupada',null,null),
('MAGALDI_1765','PB20','PB20','sector','anmat','PB',20,'ocupada',null,null),
('MAGALDI_1765','PB21','PB21','sector','anmat','PB',17,'ocupada',null,null),
('MAGALDI_1765','PB22','PB22','sector','anmat','PB',17,'ocupada',null,null),
('MAGALDI_1765','PB23','PB23','sector','anmat','PB',35,'ocupada',null,null),
('MAGALDI_1765','PB24','PB24','sector','anmat','PB',17,'ocupada',null,null),
('MAGALDI_1765','PB25','PB25','sector','anmat','PB',17,'ocupada',null,null),
('MAGALDI_1765','PB26','PB26','sector','anmat','PB',50,'ocupada',null,null),
('MAGALDI_1765','PB27','PB27','sector','anmat','PB',70,'ocupada',null,null),
('MAGALDI_1765','PB28','PB28','sector','anmat','PB',60,'ocupada',null,null),
('MAGALDI_1765','PB29','PB29','sector','anmat','PB',60,'ocupada',null,null),
('MAGALDI_1765','PB30','Depósito PB30','sector','anmat','PB',107,'disponible',null,'Único sector ANMAT disponible'),
('MAGALDI_1765','PB31','Depósito PB31','sector','anmat','PB',70,'ocupada',null,null),
('MAGALDI_1765','PB32','Depósito PB32','sector','anmat','PB',10,'ocupada',null,null),
-- ── MAGALDI 1765 · Planta Baja · Oficinas / servicios / maniobra ────────────
('MAGALDI_1765','OF-PB1','Oficinas PB1','oficina','oficinas','PB',50,'ocupada',null,null),
('MAGALDI_1765','OF-PB2','Oficinas PB2','oficina','oficinas','PB',10,'ocupada',null,null),
('MAGALDI_1765','OF-PB3','Oficinas PB3','oficina','oficinas','PB',50,'ocupada',null,null),
('MAGALDI_1765','RECEP','Recepción','oficina','oficinas','PB',null,'bloqueada',null,'uso interno'),
('MAGALDI_1765','SCOMP','Sala de Cómputos','servicio',null,'PB',null,'no_comercializable',null,null),
('MAGALDI_1765','ASERV','Área Servicio Mantenimiento','servicio',null,'PB',null,'no_comercializable',null,null),
('MAGALDI_1765','PLAYA','Playa de Maniobras','maniobra',null,'PB',820,'no_comercializable',null,'descubierto'),
('MAGALDI_1765','PLAYON','Playón de Maniobras','maniobra',null,'PB',880,'no_comercializable',null,'descubierto'),
('MAGALDI_1765','PLZ','Plazoleta de Desconsolidado','maniobra',null,'PB',null,'no_comercializable',null,'descubierto')
on conflict (site, unit_code) do nothing;
